version: "3.9"
   
services:
  db:
    image: mariadb:10.2.22
    ports:
      - "30000:3306"
    environment:
       MYSQL_DATABASE: 'digikala'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'

    volumes:
      - /tmp/db:/docker-entrypoint-initdb.d/:ro
  cron:
    build: cron-docker
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db