# Generated by Django 4.0.2 on 2022-02-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('position', models.AutoField(primary_key=True, serialize=False)),
                ('incident', models.CharField(max_length=30)),
            ],
        ),
    ]
