# Generated by Django 4.0.2 on 2022-02-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteIncidentLog',
            fields=[
                ('position', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.CharField(max_length=144)),
            ],
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident',
            field=models.CharField(max_length=144),
        ),
    ]
